import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";


function killowatthours_per_year(watt: number) {
  let hours_per_year = 24 * 365;
  return watt * hours_per_year / 1000.
  //return watt * (hours_per_year) / 1000.
}

interface WattbarProps {
  wattText: string;
  onWattChange: (value: string) => void;
}

function Wattbar(prop: WattbarProps) {
  return (
    <form>
      <input type="text" value={prop.wattText} placeholder="100" onChange={(e) => prop.onWattChange(e.target.value)} />
    </form>
  )
}

interface WattProp {
  watt: number
}

function WattResult(prop: WattProp) {
  return (
    <h1 className="text-white"> kWh = {killowatthours_per_year(prop.watt)} </h1>
  )
}
function PriceResult(prop: WattProp) {
  let price = .5
  return (
    <h1 className="text-white"> price = {killowatthours_per_year(prop.watt) * price} </h1>
  )
}

function All() {
  const [wattText, setWattText] = useState("");
  return (
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
      <Wattbar wattText={wattText} onWattChange={setWattText} />
      <WattResult watt={+wattText} />
      <PriceResult watt={+wattText} />
    </div>
  )
}


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>HomeLab Tooling</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            HomeLab Tooling
          </h1>
          <All />
        </div>
      </main>
    </>
  );
};

export default Home;
